Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

LineLength:
  Enabled: false

ClassLength:
  Enabled: false

MethodLength:
  Enabled: false

BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false